/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.milik.nmcalc.gui;

import cz.milik.nmcalc.values.ErrorValue;

/**
 *
 * @author jan
 */
public class ErrorLabel extends javax.swing.JPanel {

    private Exception exception;

    public Exception getException() {
        return exception;
    }

    public void setException(Exception exception) {
        this.exception = exception;
    }
    
    
    private ErrorValue errorValue;

    public ErrorValue getErrorValue() {
        return errorValue;
    }

    public void setErrorValue(ErrorValue errorValue) {
        this.errorValue = errorValue;
    }
    
    
    /**
     * Creates new form ErrorLabel
     */
    public ErrorLabel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        errorLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        errorLabel.setText("jLabel1");
        errorLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(errorLabel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorLabel;
    // End of variables declaration//GEN-END:variables
}
