/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.milik.nmcalc.gui;

import cz.milik.nmcalc.ErrorValue;
import cz.milik.nmcalc.ICalcValue;
import cz.milik.nmcalc.Interpreter;
import cz.milik.nmcalc.ast.ASTNode;
import cz.milik.nmcalc.gui.IInputView.IInputViewListener;
import cz.milik.nmcalc.peg.CalcParser;
import cz.milik.nmcalc.peg.ParseResult;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author jan
 */
public class SimpleForm extends javax.swing.JFrame {

    private final CalcParser parser = new CalcParser();
    private final Interpreter interpreter = new Interpreter();
    
    /**
     * Creates new form SimpleForm
     */
    public SimpleForm() {
        initComponents();
        
        inputPane.addListener(new IInputViewListener() {
            
            @Override
            public void onInput(IInputView view, String input) {
                evaluate();
            }
            
        });
    }
    
    public void evaluate()
    {
        try {
            ParseResult<ICalcValue> parsed = parser.parseList(inputPane.getInput());
            if (parsed.isSuccess()) {
                ICalcValue result = interpreter.eval(parsed.getValue());
                //outputPane.setModel(parsed.getValue());
                if (result.isError()) {
                    inputPane.setError((ErrorValue)result);
                } else {
                    outputPane.setModel(result);
                    inputPane.clearError();
                }
            } else {
                inputPane.setError(new ErrorValue(parsed.getErrorMessage()));
            }
        } catch (Exception e) {
            outputPane.setModel(new ErrorValue(e.getMessage()));
        }
        /*
        try {
            ParseResult<ASTNode> parsed = parser.parse(inputPane.getInput());
            System.err.println("Parsed: " + parsed.toString());
            if (parsed.isSuccess()) {
                ICalcValue result = interpreter.evaluate(parsed.getValue());
                System.err.println("Result: " + result.toString());
                if (result.isError()) {
                    inputPane.setError((ErrorValue)result);
                } else {
                    inputPane.clearError();
                    SimpleForm.this.outputPane.setModel(result);
                    //SimpleForm.this.outputPane.setText(result.toString());
                }
            } else {
                inputPane.setError(new ErrorValue(parsed.getErrorMessage()));
            }
        } catch (Exception e) {
            inputPane.clearError();
            outputPane.setModel(new ErrorValue(e.getMessage()));
        }
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        outputPane = new cz.milik.nmcalc.gui.SimpleCalcValueView();
        inputPane = new cz.milik.nmcalc.gui.SimpleCalcInput();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(250);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setResizeWeight(1.0);

        outputPane.setMinimumSize(new java.awt.Dimension(41, 41));
        jSplitPane1.setRightComponent(outputPane);
        jSplitPane1.setLeftComponent(inputPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimpleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimpleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimpleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimpleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimpleForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private cz.milik.nmcalc.gui.SimpleCalcInput inputPane;
    private javax.swing.JSplitPane jSplitPane1;
    private cz.milik.nmcalc.gui.SimpleCalcValueView outputPane;
    // End of variables declaration//GEN-END:variables
}
