/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.milik.nmcalc.gui;

import cz.milik.nmcalc.ErrorValue;
import cz.milik.nmcalc.utils.ListenerCollection;

/**
 *
 * @author jan
 */
public class SimpleCalcInput extends javax.swing.JPanel implements IInputView {

    private ErrorValue error;
    
    @Override
    public ErrorValue getError() {
        return error;
    }
    
    @Override
    public void setError(ErrorValue error) {
        this.error = error;
        
        if (error == null) {
            statusLabel.setVisible(false);
            return;
        }
        
        statusLabel.setVisible(true);
        statusLabel.setText(error.getMessage());
    }
    
    /**
     *
     */
    @Override
    public void clearError() {
        setError(null);
    }
    
    
    @Override
    public String getInput() {
        return input.getText();
    }

    
    private final ListenerCollection<IInputViewListener> listeners = new ListenerCollection(new IInputViewListener[] {});
    
    @Override
    public void addListener(IInputViewListener listener) {
        listeners.add(listener);
    }

    @Override
    public void removeListener(IInputViewListener listener) {
        listeners.remove(listener);
    }
    
    protected void fireOnInput(final String input) {
        listeners.handleEvent(listener -> {
            listener.onInput(this, input);
        });
    }
    
    
    /**
     * Creates new form SimpleCalcInput
     */
    public SimpleCalcInput() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        input = new javax.swing.JTextPane();
        statusLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(input);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        statusLabel.setText("jLabel1");
        add(statusLabel, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void inputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputKeyPressed
    
    }//GEN-LAST:event_inputKeyPressed

    private void inputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputKeyReleased
        this.fireOnInput(getInput());
    }//GEN-LAST:event_inputKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane input;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
}
