/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.milik.nmcalc.gui;

import cz.milik.nmcalc.ICalcValue;
import cz.milik.nmcalc.utils.IMonad;
import cz.milik.nmcalc.utils.Monad;
import java.awt.Font;

/**
 *
 * @author jan
 */
public class SimpleCalcValueView extends javax.swing.JPanel {

    private IMonad<ICalcValue> model = Monad.nothing();
    
    public IMonad<ICalcValue> getModel() {
        return model;
    }
    
    public void setModel(IMonad<ICalcValue> aModel) {
        IMonad<ICalcValue> oldModel = model;
        model = Monad.nonNull(aModel);
        onModelChanged(oldModel, model);
    }
    
    public void setModel(ICalcValue model) {
        setModel(Monad.maybe(model));
    }
    
    protected void onModelChanged(IMonad<ICalcValue> oldModel, IMonad<ICalcValue> newModel) {
        textPane.setText(newModel.unwrap(value -> value.getRepr(), "null"));
    }
    
    
    /**
     * Creates new form SimpleCalcValueView
     */
    public SimpleCalcValueView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textPane = new javax.swing.JTextPane();

        setLayout(new java.awt.BorderLayout());

        textPane.setFont(new Font(Font.MONOSPACED, Font.PLAIN, 24));
        textPane.setText("Result");
        jScrollPane1.setViewportView(textPane);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane textPane;
    // End of variables declaration//GEN-END:variables
}
